apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
stringData:
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | squote }}
  .env: |
    AUTH_SECRET={{ .Values.AUTH_SECRET | squote }}
    CHATBOT_ENV={{ .Values.CHATBOT_ENV | squote }}
    CHATBOT_PATH={{ .Values.INSTALL_PATH | squote }}
    CHATBOT_REPO_URL={{ .Values.CHATBOT_REPO_URL | squote }}
    CHATBOT_VERSION={{ .Values.CHATBOT_VERSION | squote }}
    CODEBASE_TOOL={{ .Values.CODEBASE_TOOL | squote }}
    CODEX_CODEBASE_PATH={{ .Values.CODEX_CODEBASE_PATH | squote }}
    DIVI_BRANCH={{ .Values.DIVI_BRANCH | squote }}
    DIVI_REPO_URL={{ .Values.DIVI_REPO_URL | squote }}
    GIT_REF={{ .Values.GIT_REF | squote }}
    GITHUB_TOKEN={{ .Values.GITHUB_TOKEN | squote }}
    INSTALL_PATH={{ .Values.INSTALL_PATH | squote }}
    OPENAI_API_KEY={{ .Values.OPENAI_API_KEY | squote }}
    PORT={{ .Values.PORT | squote }}
    POSTGRES_URL={{ .Values.POSTGRES_URL | squote }}
    REDIS_URL={{ .Values.REDIS_URL | squote }}
    VIRTUAL_HOST={{ .Values.VIRTUAL_HOST | squote }}

