CHATBOT_ENV:
CHATBOT_IMAGE:
CHATBOT_REPO_URL:
CHATBOT_VERSION:

AUTH_SECRET:
AUTH_URL:

CODEBASE_TOOL:
CODEX_CODEBASE_PATH:

DIVI_BRANCH:
DIVI_REPO_URL:

GITHUB_TOKEN:
GIT_REF:

INSTALL_PATH:

MEMORY_LIMIT:

OPENAI_API_KEY:

PORT: 3000

POSTGRES_URL:

REDIS_URL:

REPLICAS:

VIRTUAL_HOST:

