DEEPHIVE_ENV:
DEEPHIVE_IMAGE:

DEEPHIVE_REPO_URL:
DEEPHIVE_VERSION:

DISCORD_TOKEN:

DIVI_CODEBASE_PATH:
DIVI_REPO_URL:
DIVI_BRANCH:

GITHUB_TOKEN:
GIT_REF:
GOOGLE_SHEETS_CREDENTIALS:
INSTALL_PATH:

LANGCHAIN_API_KEY:
LANGCHAIN_ENDPOINT:
LANGCHAIN_PROJECT:
LANGSMITH_API_KEY:

MEMORY_LIMIT:

OPENAI_API_KEY:

PORT: 3000

REPLICAS:

SLACK_BOT_TOKEN:
SLACK_SIGNING_SECRET:

TAVILY_API_KEY:

VIRTUAL_HOST:

WEAVIATE_API_KEY:
WEAVIATE_HOST:
